import InstructionPage from "../components/InstructionPage";

export default function Instruction2({ navigation }) {
  return (
    <InstructionPage
      navigation={navigation}
      text="Enter the token generated by this App (the remote) into the control software and click begin. You should now recieve a notification on the remote, letting you know that you are ready to present."
      image={require("../../assets/images/instruction_2.png")}
      nextPage="Instruction3"
    />
  );
}
